/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
  /*---First Step is to Setup the main system clock SYSCLK, we will configure
  the board at maximum clock, for the board it is 180MHz---*/
  /*---We will use HSI clock which is enabled by default and is 16MHz, and then
  this is fed to PLL module by the divider "M", the PLL block will multiple this
  with "N", and the output produced can be further divided by "P".
  Note: The LTDC peripheral has a separate PLL module, and it's input is HSI/M
  so we have choose "M" properly, so basically the HSI/M output is input for
  PLL VCO (System Clock) and PLLSAI VCO (LTDC Clock)---*/


	for(;;);
}
