/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

// We will get warning due to the below line unless we disabled this warning
// Right Click Project --> Properties --> C/C++ Build --> Settings --> Tool Settings
// --> Then in MCU Settings --> Set Floating Point Unit as None And
// Floating Point ABI as Software Implenmentation
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
  // This is only applicable for Cortex M3/M4/M7 or higher micro-controllers
  // printf works over SWO (Serial Wire Output) pin of the SWD interface.
  // If we have a board based on Cortex-M0/M0+ then we have to use OpenOCD
  // based semi-hosting technique to use printf

  // In ARM Cortex-M4 processor there is a Unit called as ITM.
  // ITM means Instrumentation Trace Macrocell Unit.
  // The ITM is an optional application driven trace source that supports printf
  // style debugging to trace operating system and application events, and
  // generates diagnostic system information.
  // And this unit is not available in Cortex-M0/M0+ processor.
  printf("Hello World\n");
	for(;;);
}
