/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Function Prototypes
extern void initialise_monitor_handles( void );

int main(void)
{
  // Implementation of printf feature using ARM Cortex M3/M4 ITM functionality
  // is only limited to high-end processors such as Cortex M3/M4/M7
  // So in case we wanted to use the printf functionality for debugging on
  // Cortex M0/M0+ we can use OpenOCD based Semi-Hosting
  // Here we have to update the linker arguments with the following flags
  // "-specs=rdimon.specs -lc -lrdimon"
  // Instead of using St-Link Debugger, we have to use St-Link (OpenOCD)
  // and then we need to call the function "initialise_monitor_handles()" at
  // start-up and simply use printf function with \n character at last
  // Apart from this while debugging the project we have to use ST-Link Open OCD
  // as debugger, and in the startup section of the debugger we have to mention
  // "monitor arm semihosting enable"
  // else semihosting will not work, don't forget to exclude syscalls.c from build

  initialise_monitor_handles();

  // Note: Here \n is very important
  printf("Hello World using Semi-Hosting\n");
  /* Loop forever */
	for(;;);
}
